#!/bin/bash

cp /home/guerrero/Documents/UNAM/3RD-SEMESTER/Computacion_I/ProyectoComp1.01/cmake-build-debug/inventory.csv /run/user/1000/gvfs/google-drive:host=gmail.com,user=joseguerrero21012/0AN6cFWrw0bztUk9PVA/1Os7QRywS4mzJBn2vnlHWc6wa-VR2H4C2/1iPro1zYdv-nHpI4uQa-izqxg6k9is6-0/19vWlAw-dATiGHERJWQBGgxbrUQFQaliu
